---
name: Conduit
version: 1.0.0
stage: stable
slug: conduit
description: >-
  A simple, fast and reliable chat server powered by matrix
url: https://github.com/velvet-lab/hassio-addons/tree/main/conduit
arch:
  - amd64
  - aarch64
codenotary: info@velvet-lab.org
host_network: false
startup: system
hassio_role: default
hassio_api: true
homeassistant: 2026.1.0
init: false
apparmor: true
map:
  - type: homeassistant_config
    read_only: false
backup: cold
backup_exclude:
  - /data/app.err
watchdog: tcp://[HOST]:[PORT:8000]
ports:
  8000/tcp: 8000
  8448/tcp: 8448
options:
  server_name: homeassistant.local
schema:
  server_name: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
