---
name: Conduit
version: 1.0.0
stage: stable
slug: conduit
description: >-
  A simple, fast and reliable chat server powered by matrix
url: https://github.com/velvet-lab/hassio-addons/tree/main/conduit
arch:
  - amd64
  - aarch64
codenotary: info@velvet-lab.org
host_network: false
startup: system
hassio_role: default
hassio_api: true
homeassistant: 2026.1.0
init: false
apparmor: true
backup: cold
backup_exclude:
  - /data/app.err
watchdog: tcp://[HOST]:[PORT:8000]
ports:
  8000/tcp: 8000
  8448/tcp: 8448
options:
  server_name: null
schema:
  server_name: str
  allow_registration: bool?
  allow_federation: bool?
  allow_encryption: bool?
  allow_room_creation: bool?
  allow_unstable_room_versions: bool?
  default_room_version: str?
  max_concurrent_requests: int?
  max_request_size: int?
  registration_token: password?
  retention_default_accessed: str?
  retention_default_created: str?
  retention_default_space: str?
  retention_remote_accessed: str?
  retention_remote_created: str?
  retention_remote_space: str?
  retention_local_accessed: str?
  retention_local_created: str?
  retention_local_space: str?
  retention_thumbnail_accessed: str?
  retention_thumbnail_created: str?
  retention_thumbnail_space: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
