---
name: Neo4j (experimental)
version: 0.3.0
stage: experimental
slug: neo4j
description: >-
  Neo4j is a graph database. This add-on runs a self-hosted Neo4j instance.
url: https://github.com/velvet-lab/hassio-addons/tree/main/neo4j
arch:
  - amd64
  - aarch64
host_network: false
startup: services
hassio_role: default
homeassistant: 2026.1.0
init: false
apparmor: true
map:
  - type: homeassistant_config
    read_only: false
backup: hot
backup_exclude:
  - /data/app.err
watchdog: tcp://[HOST]:[PORT:7474]
ports:
  7474/tcp: 7474
  7473/tcp: null
  7687/tcp: null
options:
  log_level: info
  initial_password: null
  usage_report_enabled: false
  apoc_enabled: true
  dbms_security_procedures_unrestricted: "apoc.*"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  initial_password: password
  usage_report_enabled: bool
  apoc_enabled: bool
  dbms_security_procedures_unrestricted: str?
