---
name: RustFS
version: 0.5.2
stage: stable
slug: rustfs
description: >-
  High-performance enterprise-grade distributed file system and S3 compatible object storage solution written in Rust.
url: https://github.com/velvet-lab/hassio-addons/tree/main/rustfs
arch:
  - amd64
  - aarch64
startup: system
homeassistant: 2026.1.0
init: false
apparmor: true
backup: hot
backup_exclude:
  - /data/app.err
  - /data/logs/*
watchdog: tcp://[HOST]:[PORT:8080]
ports:
  8080/tcp: 8080
  8081/tcp: 8081
options:
  access_key: admin
  secret_key: null
  console_enable: true
schema:
  access_key: str
  secret_key: password
  console_enable: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
