---
name: Dns/Dhcp Server
version: 1.0.0
stage: experimental
slug: dns
description: >-
  Self host a Dns/Dhcp server for privacy & security
url: https://git.x-breitschaft.de/smarthome/hassio-addons
arch:
  - amd64
codenotary: breitschaftroland@gmail.com
host_network: false
startup: system
init: false
advanced: true
apparmor: true
panel_admin: true
backup: hot
ports:
  5380/tcp: 5380
  53/tcp: 53
  53/udp: 53
  67/udp: 67
  68/udp: 68
  8053/tcp: null
options:
  DNS_SERVER_DOMAIN: homeassistant.local
  DNS_SERVER_ADMIN_PASSWORD: null
  DNS_SERVER_FORWARDERS: null
  DNS_SERVER_LOG_USING_LOCAL_TIME: true
schema:
  DNS_SERVER_DOMAIN: str
  DNS_SERVER_ADMIN_PASSWORD: password
  DNS_SERVER_PREFER_IPV6: bool?
  DNS_SERVER_OPTIONAL_PROTOCOL_DNS_OVER_HTTP: bool?
  DNS_SERVER_RECURSION: list(Allow|Deny|AllowOnlyForPrivateNetworks|UseSpecifiedNetworks)?
  DNS_SERVER_RECURSION_DENIED_NETWORKS: str?
  DNS_SERVER_RECURSION_ALLOWED_NETWORKS: str?
  DNS_SERVER_ENABLE_BLOCKING: bool?
  DNS_SERVER_ALLOW_TXT_BLOCKING_REPORT: bool?
  DNS_SERVER_BLOCK_LIST_URLS: str?
  DNS_SERVER_FORWARDERS: str
  DNS_SERVER_FORWARDER_PROTOCOL: list(Udp|Tcp|Tls|Https|HttpsJson)
  DNS_SERVER_LOG_USING_LOCAL_TIME: bool
  debug: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
watchdog: tcp://[HOST]:53
webui: "http://[HOST]:[PORT:5380]"
