---
name: Dns/Dhcp Server
version: 10.0.1
slug: dns
description: >-
  Self host a Dns/Dhcp server for privacy & security
url: https://git.x-breitschaft.de/smarthome/hassio-addons
arch:
  - amd64
codenotary: breitschaftroland@gmail.com
host_network: false
startup: system
init: false
advanced: true
apparmor: true
map:
  - config:rw
ports:
  5380/tcp: 5380
  53/tcp: 53
  53/udp: 53
  67/udp: 67
  68/udp: 68
schema:
  debug: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
watchdog: tcp://[HOST]:5380
webui: "http://[HOST]:[PORT:5380]"
