---
name: LiteLLM (experimental)
version: 0.2.3
stage: experimental
slug: litellm
description: >-
  LiteLLM is an open source AI Gateway that provides a unified interface to 100+ LLM providers
  (OpenAI, Anthropic, Bedrock, Azure, Gemini, etc.) with cost tracking, load balancing, and an admin dashboard
url: https://github.com/velvet-lab/hassio-addons/tree/main/litellm
arch:
  - amd64
  - aarch64
host_network: false
startup: application
hassio_role: default
homeassistant: 2026.1.0
init: false
apparmor: true
map:
  - type: homeassistant_config
    read_only: false
services:
  - mysql:want
backup: hot
backup_exclude:
  - /data/app.err
  - /data/litellm/database.db-shm
  - /data/litellm/database.db-wal
watchdog: tcp://[HOST]:[PORT:4000]
ports:
  4000/tcp: 4000
options:
  log_level: info
  master_key: null
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  master_key: password
  ui_enable: bool?
  use_mysql: bool?
  store_model_in_db: bool?
  redis_host: "str?"
  redis_port: "port?"
  redis_password: "password?"
  redis_db: "int?"
