---
name: Technitium DNS Server
version: 10.0.1
slug: technitium
description: >-
  Self host a DNS server for privacy & security
url: https://git.x-breitschaft.de/smarthome/hassio-addons
arch:
  - amd64
codenotary: breitschaftroland@gmail.com
host_network: false
startup: system
init: true
advanced: true
ports:
  5380/tcp: 5380
  53/tcp: 53
  53/udp: 53
  8053/tcp: null
  853/tcp: null
  80/tcp: null
  443/tcp: null
options:
  hetzner_api_token: null
schema:
  hetzner_api_token: password?
  debug: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
watchdog: tcp://[HOST]:5380
webui: "http://[HOST]:[PORT:5380]"
