net:
  port: 27017
  bindIpAll: true
  ipv6: false
  unixDomainSocket:
    enabled: false
  tls:
    mode: disabled

processManagement:
  pidFilePath: /run/mongodb/mongod.pid
  timeZoneInfo: /usr/share/zoneinfo

operationProfiling:
  mode: off

# Where and how to store data.
storage:
  dbPath: ${DATA_ROOT}
  directoryPerDB: true

systemLog:
  verbosity: 0
  quiet: false