---
name: MongoDB
version: 2.0.6
stage: stable
slug: mongodb
description: >-
  MongoDB is a source-available, cross-platform, document-oriented database program
url: https://github.com/velvet-lab/hassio-addons/tree/main/mongodb
arch:
  - amd64
  - aarch64
codenotary: info@velvet-lab.org
host_network: false
startup: system
hassio_role: default
hassio_api: true
homeassistant: 2025.05.5
homeassistant_api: true
init: false
apparmor: true
backup: cold
backup_exclude:
  - "/data/app.err"
watchdog: tcp://[HOST]:27017
ports:
  27017/tcp: 27017
schema:  
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  repl_enabled: bool?
  auth_enabled: bool?
  admin_password: password?
