---
name: DynDns
version: 0.1.2
stage: experimental
slug: dyndns
description: >-
  DynDns Updater for Hetzner Dns Server
url: https://github.com/rolbre/hassio-addons/tree/main/dyndns
arch:
  - amd64
codenotary: breitschaftroland@gmail.com
host_network: false
startup: services
init: false
advanced: true
apparmor: true
homeassistant: 2022.11.0
panel_admin: true
backup: hot
options:
  api_token: null
  records:
    - domain: "my-domain.com"
      name: www
      ttl: 3600
      type: A
  interval: 1h
  log_level: info
schema:
  api_token: str
  interval: str
  records:
    - domain: str
      name: str
      ttl: int?
      type: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
