---
name: Rocket.Chat
version: 1.0.0
stage: stable
slug: rocketchat
description: >-
  Bring together messaging, voice, video, critical apps, and AI to keep teams connected and missions protected.
url: https://github.com/velvet-lab/hassio-addons/tree/main/rocket.chat
arch:
  - amd64
  - aarch64
codenotary: info@velvet-lab.org
host_network: true
startup: system
homeassistant: 2025.05.5
init: false
advanced: true
apparmor: true
panel_admin: true
backup: cold
backup_exclude:
  - "/data/app.err"
watchdog: tcp://[HOST]:3000
webui: http://[HOST]:[PORT:3000]
map:
  - type: addon_config
    read_only: false
ports:
  3000/tcp: 3000
schema:
  root_url: str?
  mongo_url: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?  
    
    