---
name: Portainer
version: 1.0.0
stage: stable
slug: portainer
description: >-
  Empower your team to build, operate, and scale containerized environments with precision
url: https://github.com/velvet-lab/hassio-addons/tree/main/davis
arch:
  - amd64
  - aarch64
codenotary: info@velvet-lab.org
startup: services
homeassistant: 2026.1.0
init: false
apparmor: true
tmpfs: true
backup: hot
backup_exclude:
  - /data/app.err
watchdog: tcp://[HOST]:[PORT:43209]
ports:
  43209/tcp: 43209
  16464/tcp: 16464
options:
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
