# Generic application settings
APP_ENV=prod
APP_TIMEZONE=${APP_TIMEZONE}
LOG_FILE_PATH=/data/davis/logs/app.log
BIRTHDAY_REMINDER_OFFSET=${BIRTHDAY_REMINDER_OFFSET}
CALDAV_ENABLED=${CALDAV_ENABLED}
CARDDAV_ENABLED=${CARDDAV_ENABLED}
WEBDAV_ENABLED=${WEBDAV_ENABLED}
PUBLIC_CALENDARS_ENABLED=${PUBLIC_CALENDARS_ENABLED}

# Database settings
DATABASE_DRIVER=${DATABASE_DRIVER}
DATABASE_URL=${DATABASE_URL}

# Authentication settings for the Davis admin interface
ADMIN_LOGIN=${ADMIN_LOGIN}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_AUTH_BYPASS=false
AUTH_METHOD=Basic
AUTH_REALM=DavisDAV

# WebDAV settings
WEBDAV_TMP_DIR=/tmp
WEBDAV_PUBLIC_DIR=/data/davis/public
WEBDAV_HOMES_DIR=${HOME_DIR}

# Mail settings
INVITE_FROM_ADDRESS=${INVITE_FROM_ADDRESS}
MAIL_HOST=${MAIL_HOST}
MAIL_PORT=${MAIL_PORT}
MAIL_USERNAME=${MAIL_USERNAME}
MAIL_PASSWORD=${MAIL_PASSWORD}

# Trust the immediate proxy for X-Forwarded-* headers including HTTPS detection
SYMFONY_TRUSTED_PROXIES=${TRUSTED_PROXIES}

