---
name: SearXNG (experimental)
version: 2026.8.21
stage: experimental
slug: searxng
description: >-
  SearXNG is a free, self-hosted metasearch engine that aggregates results
  from many search services without tracking or profiling its users
url: https://github.com/velvet-lab/hassio-addons/tree/main/searxng
arch:
  - amd64
  - aarch64
host_network: false
startup: application
hassio_role: default
homeassistant: 2026.1.0
init: false
apparmor: true
map:
  - type: homeassistant_config
    read_only: false
backup: hot
backup_exclude:
  - /data/app.err
watchdog: tcp://[HOST]:[PORT:8888]
ports:
  8888/tcp: 8888
options:
  log_level: info
  instance_name: "Privat-SearXNG"
  secret_key: null
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  instance_name: "str?"
  secret_key: password
  external_url: "str?"
  redis_host: "str?"
  redis_port: "port?"
  redis_password: "password?"
  redis_username: "str?"
  redis_db: "int?"
