---
name: Gogs (experimental)
version: 0.14.3
stage: experimental
slug: gogs
description: >-
  Gogs is a painless self-hosted Git service written in Go
url: https://github.com/velvet-lab/hassio-addons/tree/main/gogs
arch:
  - amd64
  - aarch64
host_network: false
hassio_api: true
startup: system
hassio_role: default
homeassistant: 2026.1.0
init: false
apparmor: true
map:
  - type: homeassistant_config
    read_only: false
backup: hot
backup_exclude:
  - /data/app.err
watchdog: tcp://[HOST]:[PORT:3000]
ports:
  3000/tcp: 3000
options:
  log_level: info
  secret_key: null
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  secret_key: password
  redis_enabled: bool?
  redis_host: str?
  redis_port: int?
  redis_password: "password?"